[package]
name = "ai"
version = "0.0.0"
edition = "2021"

[lib]
test = false
doctest = false

[dependencies]
data = { path = "../data", version = "0.0.0" }
rules = { path = "../rules", version = "0.0.0" }

petgraph = "0.6.4"
rand = "0.8.5"